/**
 * F2 — bundle the TokenMaxed OpenCode adapter. Mirrors packages/codex-plugin:
 * ONE self-contained MCP server bundle + ONE self-contained plugin file +
 * reference data + generated commands, all COMMITTED (installs ship only
 * tracked files).
 *
 * OpenCode contracts (verified v1.17, July 2026):
 *   - MCP server: registered in opencode.json under `mcp.tokenmaxed` with
 *     `environment: { TOKENMAXED_HOST: "opencode" }` (see opencode.example.jsonc).
 *     Tools surface as `tokenmaxed_router_*` (server_tool sanitization).
 *   - Plugin: a single JS file users copy into `.opencode/plugin/` (project) or
 *     `~/.config/opencode/plugin/` (global). Runs IN-PROCESS under Bun, so the
 *     bundle must NOT mutate process.env for host identity (the plugin passes
 *     TOKENMAXED_HOST explicitly; see mcp/src/opencode-plugin.ts).
 *   - Commands: markdown in `.opencode/command/` → /tokenmaxed-<name>. Generated
 *     from the Claude plugin's skills (single source of truth) with tool-name
 *     (mcp__plugin_tokenmaxed_tokenmaxed__X → tokenmaxed_X) + command-reference
 *     (/tokenmaxed:x → /tokenmaxed-x) + host-language transforms. Commands are
 *     USER-invoked by construction, which preserves the manual-only semantics of
 *     the state-changing skills without an extra guard file.
 */

import { build } from 'esbuild';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const mcpSrc = (f) => resolve(root, '../mcp/src', f);

const SHIM = [
  "import { createRequire as __cr } from 'node:module';",
  "import { fileURLToPath as __f } from 'node:url';",
  "import { dirname as __d } from 'node:path';",
  'const require = __cr(import.meta.url);',
  'const __filename = __f(import.meta.url);',
  'const __dirname = __d(__filename);',
].join('\n');

// Reference data + starters (same set the other host adapters ship).
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

// The MCP server bundle: launched by opencode.json (a child process, so the
// host-identity env default banner is correct here — explicit env still wins).
await build({
  entryPoints: [mcpSrc('bin.ts')],
  outfile: resolve(root, 'server/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/opencode-plugin/build.mjs — DO NOT EDIT. Bundled TokenMaxed MCP server (OpenCode).\n${SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'opencode';`,
  },
});
console.error('[opencode-plugin] bundled MCP server → server/index.mjs');

// The lifecycle plugin bundle: runs IN-PROCESS in OpenCode (Bun) — NO env
// mutation banner (it would leak the default into the whole host process; the
// plugin threads TOKENMAXED_HOST explicitly instead).
await build({
  entryPoints: [mcpSrc('opencode-plugin.ts')],
  outfile: resolve(root, 'plugin/tokenmaxed.js'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/opencode-plugin/build.mjs — DO NOT EDIT. TokenMaxed OpenCode plugin (banner + routing gate + review loop).\n${SHIM}`,
  },
});
console.error('[opencode-plugin] bundled plugin → plugin/tokenmaxed.js');

// The review CHILD (spawned by the plugin so the spawnSync-based review path
// never blocks OpenCode's shared event loop). Ships NEXT TO the plugin file —
// installs must copy both. A child process, so the host-identity env default
// banner is correct here too.
await build({
  entryPoints: [mcpSrc('review-child-main.ts')],
  outfile: resolve(root, 'plugin/tokenmaxed-review.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/opencode-plugin/build.mjs — DO NOT EDIT. TokenMaxed review child (OpenCode).\n${SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'opencode';`,
  },
});
console.error('[opencode-plugin] bundled review child → plugin/tokenmaxed-review.mjs');

// --- generate commands from the Claude plugin's skills (single source) ---------
const srcSkills = resolve(root, '../plugin/skills');
const outCommands = resolve(root, 'command');
rmSync(outCommands, { recursive: true, force: true });
mkdirSync(outCommands, { recursive: true });

// ONE transform applied to body AND description alike (a description like
// "Claude stops delegating" must not survive either).
const transform = (text) =>
  text
    // Tool names: Claude Code plugin-MCP format → OpenCode server_tool sanitization.
    .replaceAll('mcp__plugin_tokenmaxed_tokenmaxed__', 'tokenmaxed_')
    // Command references: /tokenmaxed:foo → /tokenmaxed-foo (OpenCode command names).
    .replaceAll(/\/tokenmaxed:([a-z-]+)/g, '/tokenmaxed-$1')
    // Host-language transforms (Claude-Code-specific instructions would be
    // wrong inside OpenCode; keep lane NAMES like "cheaper-Claude" untouched).
    .replaceAll('Use the AskUserQuestion tool', 'Ask the user directly')
    .replaceAll('the AskUserQuestion tool', 'a direct question to the user')
    .replaceAll('start Claude Code', 'start OpenCode')
    .replaceAll('Claude stops delegating', 'the agent stops delegating')
    .replaceAll("Claude's `--dangerously-skip-permissions`", "Claude Code's `--dangerously-skip-permissions`")
    .replaceAll('Claude offloads', 'the agent offloads')
    .replaceAll('Claude invokes', 'the agent invokes')
    .replaceAll('Claude Code settings', 'OpenCode opencode.json')
    .replaceAll('in Claude Code', 'in OpenCode');

for (const dir of readdirSync(srcSkills)) {
  const md = readFileSync(resolve(srcSkills, dir, 'SKILL.md'), 'utf8');
  const description = transform(/^description:\s*(.+)$/m.exec(md)?.[1] ?? `TokenMaxed ${dir}`);
  // Strip the Claude frontmatter entirely; commands carry their own minimal one.
  const body = md.replace(/^---\n[\s\S]*?\n---\n/, '');
  const out = `---\ndescription: ${description}\n---\n` + transform(body);
  writeFileSync(resolve(outCommands, `tokenmaxed-${dir}.md`), out, 'utf8');
}
console.error(`[opencode-plugin] generated ${readdirSync(outCommands).length} commands → ${outCommands}`);
