/**
 * F5 — bundle the TokenMaxed Hermes adapter (hermes-agent >= 0.18.0 for the
 * pre_verify review; the gate + banner work on earlier 0.13+ shell-hook
 * versions and simply do less).
 *
 * Hermes contracts (verified v0.18.x, July 2026):
 *   - MCP: ~/.hermes/config.yaml mcp_servers.tokenmaxed with a per-server env
 *     map (Hermes passes ONLY the explicit env + an 8-var safe baseline to
 *     stdio children — the recipe's TOKENMAXED_HOST=hermes is authoritative).
 *     Tools surface as mcp_tokenmaxed_router_*.
 *   - Shell hooks: per-event subprocesses, stdin JSON → stdout JSON directive,
 *     declared under `hooks:` in config.yaml, run via `command:` (shlex-split,
 *     so "node /abs/path/x.cjs" works — .cjs parses as CJS everywhere, no
 *     extensionless dual-scope gymnastics needed on this host). FAIL OPEN.
 *   - Skills: AgentSkills SKILL.md, loadable WITHOUT copying via
 *     skills.external_dirs pointing at this package's skills/ dir; every skill
 *     auto-becomes /skill-name. No manual-only frontmatter flag ⇒ the
 *     MANUAL-ONLY body preamble carries those semantics (same as Cline).
 */

import { build } from 'esbuild';
import { chmodSync, copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const mcpSrc = (f) => resolve(root, '../mcp/src', f);

const ESM_SHIM = [
  "import { createRequire as __cr } from 'node:module';",
  "import { fileURLToPath as __f } from 'node:url';",
  "import { dirname as __d } from 'node:path';",
  'const require = __cr(import.meta.url);',
  'const __filename = __f(import.meta.url);',
  'const __dirname = __d(__filename);',
].join('\n');

// Reference data + starters (same set the other host adapters ship).
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

// The MCP server bundle (ESM — launched by path from config.yaml).
await build({
  entryPoints: [mcpSrc('bin.ts')],
  outfile: resolve(root, 'server/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/hermes-plugin/build.mjs — DO NOT EDIT. Bundled TokenMaxed MCP server (Hermes).\n${ESM_SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'hermes';`,
  },
});
console.error('[hermes-plugin] bundled MCP server → server/index.mjs');

// Hook bundles: .cjs (unambiguous CJS on every node), shebang + exec bit for
// direct execution too; import.meta.url defined to a __filename shim.
async function bundleHook(entry, name, label) {
  const outfile = resolve(root, 'hooks', name);
  await build({
    entryPoints: [mcpSrc(entry)],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    define: { 'import.meta.url': '__importMetaUrl' },
    banner: {
      js: [
        '#!/usr/bin/env node',
        `// Generated by packages/hermes-plugin/build.mjs — DO NOT EDIT. ${label}.`,
        "const __importMetaUrl = require('node:url').pathToFileURL(__filename).href;",
        "process.env.TOKENMAXED_HOST ??= 'hermes';",
      ].join('\n'),
    },
  });
  chmodSync(outfile, 0o755);
  console.error(`[hermes-plugin] bundled ${label} → hooks/${name}`);
}
await bundleHook('hook-hermes-pretoolcall.ts', 'pre-tool-call.cjs', 'TokenMaxed pre_tool_call gate (Hermes)');
await bundleHook('hook-hermes-prellmcall.ts', 'pre-llm-call.cjs', 'TokenMaxed pre_llm_call banner (Hermes)');
await bundleHook('hook-hermes-preverify.ts', 'pre-verify.cjs', 'TokenMaxed pre_verify review (Hermes)');

// --- generate skills from the Claude plugin's (single source of truth) ---------
const srcSkills = resolve(root, '../plugin/skills');
const outSkills = resolve(root, 'skills');
rmSync(outSkills, { recursive: true, force: true });
mkdirSync(outSkills, { recursive: true });

// ONE transform applied to body AND description alike.
const transform = (text) =>
  text
    // Tool names: Claude plugin-MCP format → Hermes mcp_<server>_<tool> naming.
    .replaceAll('mcp__plugin_tokenmaxed_tokenmaxed__', 'mcp_tokenmaxed_')
    // Command references: /tokenmaxed:foo → /tokenmaxed-foo (skills auto-become
    // dash-named slash commands in Hermes).
    .replaceAll(/\/tokenmaxed:([a-z-]+)/g, '/tokenmaxed-$1')
    .replaceAll('Use the AskUserQuestion tool', 'Ask the user directly')
    .replaceAll('the AskUserQuestion tool', 'a direct question to the user')
    .replaceAll('start Claude Code', 'start Hermes')
    .replaceAll('Claude stops delegating', 'the agent stops delegating')
    .replaceAll("Claude's `--dangerously-skip-permissions`", "Claude Code's `--dangerously-skip-permissions`")
    .replaceAll('Claude offloads', 'the agent offloads')
    .replaceAll('Claude invokes', 'the agent invokes')
    .replaceAll('Claude Code settings', 'Hermes config.yaml')
    .replaceAll('in Claude Code', 'in Hermes');

const MANUAL_ONLY_NOTE =
  '> **MANUAL-ONLY:** run this skill only when the user EXPLICITLY invokes it ' +
  '(e.g. `/<skill-name>`) or explicitly asks for exactly this action. Never ' +
  'auto-activate it from task matching.\n\n';

for (const dir of readdirSync(srcSkills)) {
  const md = readFileSync(resolve(srcSkills, dir, 'SKILL.md'), 'utf8');
  const name = `tokenmaxed-${dir}`;
  const manualOnly = /^disable-model-invocation:\s*true/m.test(md);
  let out = transform(md)
    // Hermes's AgentSkills frontmatter has no manual-only flag — the Claude
    // flag is dropped; its semantics survive as the explicit body preamble.
    .replace(/^disable-model-invocation:.*\n/m, '');
  out = out.replace(/^---\n/, `---\nname: ${name}\n`);
  if (manualOnly) out = out.replace(/\n---\n/, `\n---\n\n${MANUAL_ONLY_NOTE}`);
  mkdirSync(resolve(outSkills, name), { recursive: true });
  writeFileSync(resolve(outSkills, name, 'SKILL.md'), out, 'utf8');
}
console.error(`[hermes-plugin] generated ${readdirSync(outSkills).length} skills → ${outSkills}`);
