/**
 * Bundle the TokenMaxed MCP server into ONE self-contained ESM file at
 * `server/index.mjs`, so the plugin runs with no node_modules / no sibling
 * workspace at install time (plugin.json points `node ${CLAUDE_PLUGIN_ROOT}/
 * server/index.mjs`).
 *
 * Entry is the MCP source (`packages/mcp/src/bin.ts`); esbuild resolves
 * `@tokenmaxed/core` + `/node` to their built dist and inlines the MCP SDK and
 * `yaml`. Run after the workspace build so core's dist exists (root `npm run
 * build` orders core → … → plugin).
 *
 * The output `server/index.mjs` is COMMITTED — it is the self-contained install
 * artifact (a marketplace/git-tag install ships only tracked files, and
 * plugin.json launches `${CLAUDE_PLUGIN_ROOT}/server/index.mjs`). Rebuild and
 * commit it whenever the MCP server or core changes.
 */

import { build } from 'esbuild';
import { copyFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const entry = resolve(root, '../mcp/src/bin.ts');
const outfile = resolve(root, 'server/index.mjs');

// Ship a default price table with the plugin (reference data the delegate path
// needs to cost routed work). plugin.json points TOKENMAXED_PRICES at it.
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));

await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  // Some bundled CJS deps reference `require`/`__dirname` under ESM output;
  // recreate them from import.meta so the single file runs under `node`.
  banner: {
    js: [
      '// Generated by packages/plugin/build.mjs — DO NOT EDIT. Bundled TokenMaxed MCP server.',
      "import { createRequire as __cr } from 'node:module';",
      "import { fileURLToPath as __f } from 'node:url';",
      "import { dirname as __d } from 'node:path';",
      'const require = __cr(import.meta.url);',
      'const __filename = __f(import.meta.url);',
      'const __dirname = __d(__filename);',
    ].join('\n'),
  },
});

console.error(`[plugin] bundled MCP server → ${outfile}`);
