/**
 * Bundle the TokenMaxed MCP server into ONE self-contained ESM file at
 * `server/index.mjs`, so the plugin runs with no node_modules / no sibling
 * workspace at install time (plugin.json points `node ${CLAUDE_PLUGIN_ROOT}/
 * server/index.mjs`).
 *
 * Entry is the MCP source (`packages/mcp/src/bin.ts`); esbuild resolves
 * `@tokenmaxed/core` + `/node` to their built dist and inlines the MCP SDK and
 * `yaml`. Run after the workspace build so core's dist exists (root `npm run
 * build` orders core → … → plugin).
 *
 * The output `server/index.mjs` is COMMITTED — it is the self-contained install
 * artifact (a marketplace/git-tag install ships only tracked files, and
 * plugin.json launches `${CLAUDE_PLUGIN_ROOT}/server/index.mjs`). Rebuild and
 * commit it whenever the MCP server or core changes.
 */

import { build } from 'esbuild';
import { copyFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const entry = resolve(root, '../mcp/src/bin.ts');
const outfile = resolve(root, 'server/index.mjs');
const hookEntry = resolve(root, '../mcp/src/hook-pretooluse.ts');
const hookOut = resolve(root, 'hooks/pretooluse.mjs');
const stopEntry = resolve(root, '../mcp/src/hook-stop.ts');
const stopOut = resolve(root, 'hooks/stop.mjs');
const sessionEntry = resolve(root, '../mcp/src/hook-sessionstart.ts');
const sessionOut = resolve(root, 'hooks/sessionstart.mjs');
const statuslineEntry = resolve(root, '../mcp/src/statusline-main.ts');
const statuslineOut = resolve(root, 'statusline.mjs');

// Ship a default price table with the plugin (reference data the delegate path
// needs to cost routed work). plugin.json points TOKENMAXED_PRICES at it.
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
// Ship the starter configs next to the server bundle so /tokenmaxed:setup can
// create ~/.tokenmaxed/{lanes,policy}.yaml (resolved module-relative, ../).
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  // Some bundled CJS deps reference `require`/`__dirname` under ESM output;
  // recreate them from import.meta so the single file runs under `node`.
  banner: {
    js: [
      '// Generated by packages/plugin/build.mjs — DO NOT EDIT. Bundled TokenMaxed MCP server.',
      "import { createRequire as __cr } from 'node:module';",
      "import { fileURLToPath as __f } from 'node:url';",
      "import { dirname as __d } from 'node:path';",
      'const require = __cr(import.meta.url);',
      'const __filename = __f(import.meta.url);',
      'const __dirname = __d(__filename);',
      "process.env.TOKENMAXED_HOST ??= 'claude-code'; // F: host identity default (hooks don't inherit mcpServers.env)",
    ].join('\n'),
  },
});

console.error(`[plugin] bundled MCP server → ${outfile}`);

// Bundle the PreToolUse backstop hook into a single committed file too.
await build({
  entryPoints: [hookEntry],
  outfile: hookOut,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: { js: ['// Generated by packages/plugin/build.mjs — DO NOT EDIT. TokenMaxed PreToolUse hook.', "process.env.TOKENMAXED_HOST ??= \'claude-code\'; // F: host identity default (hooks don\'t inherit mcpServers.env)"].join('\n') },
});

console.error(`[plugin] bundled PreToolUse hook → ${hookOut}`);

// The Stop gate bundles core + core/node (it runs the manager review), so it
// needs the same require/__dirname shim as the server.
await build({
  entryPoints: [stopEntry],
  outfile: stopOut,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: [
      '// Generated by packages/plugin/build.mjs — DO NOT EDIT. TokenMaxed Stop gate.',
      "import { createRequire as __cr } from 'node:module';",
      "import { fileURLToPath as __f } from 'node:url';",
      "import { dirname as __d } from 'node:path';",
      'const require = __cr(import.meta.url);',
      'const __filename = __f(import.meta.url);',
      'const __dirname = __d(__filename);',
      "process.env.TOKENMAXED_HOST ??= 'claude-code'; // F: host identity default (hooks don't inherit mcpServers.env)",
    ].join('\n'),
  },
});

console.error(`[plugin] bundled Stop gate → ${stopOut}`);

// The SessionStart banner bundles core + core/node (it reads the ledger + registry
// and probes availability locally), so it needs the same require/__dirname shim.
await build({
  entryPoints: [sessionEntry],
  outfile: sessionOut,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: [
      '// Generated by packages/plugin/build.mjs — DO NOT EDIT. TokenMaxed SessionStart banner.',
      "import { createRequire as __cr } from 'node:module';",
      "import { fileURLToPath as __f } from 'node:url';",
      "import { dirname as __d } from 'node:path';",
      'const require = __cr(import.meta.url);',
      'const __filename = __f(import.meta.url);',
      'const __dirname = __d(__filename);',
      "process.env.TOKENMAXED_HOST ??= 'claude-code'; // F: host identity default (hooks don't inherit mcpServers.env)",
    ].join('\n'),
  },
});

console.error(`[plugin] bundled SessionStart banner → ${sessionOut}`);

// The statusline gauge bundles core + core/node (ledger + lane reads only — no
// probes/network by design), so it needs the same require/__dirname shim.
await build({
  entryPoints: [statuslineEntry],
  outfile: statuslineOut,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: [
      '// Generated by packages/plugin/build.mjs — DO NOT EDIT. TokenMaxed statusline gauge.',
      "import { createRequire as __cr } from 'node:module';",
      "import { fileURLToPath as __f } from 'node:url';",
      "import { dirname as __d } from 'node:path';",
      'const require = __cr(import.meta.url);',
      'const __filename = __f(import.meta.url);',
      'const __dirname = __d(__filename);',
      "process.env.TOKENMAXED_HOST ??= 'claude-code'; // F: host identity default (hooks don't inherit mcpServers.env)",
    ].join('\n'),
  },
});

console.error(`[plugin] bundled statusline gauge → ${statuslineOut}`);
