#!/usr/bin/env node
// Generated by packages/plugin/build.mjs — DO NOT EDIT. TokenMaxed PreToolUse hook.

// ../mcp/src/hook-pretooluse.ts
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ../mcp/src/hook.ts
var PRETOOLUSE_DENY_REASON = "TokenMaxed routing is disabled for this project (/tokenmaxed:off). Handle this task on the host model, or run /tokenmaxed:on to re-enable.";
function preToolUseDecision(routingEnabled) {
  if (routingEnabled) return null;
  return {
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: PRETOOLUSE_DENY_REASON
    }
  };
}

// ../mcp/src/toggle.ts
var ENABLED_BY_DEFAULT = true;
function asMap(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
  const out = /* @__PURE__ */ Object.create(null);
  for (const [k, v] of Object.entries(raw)) {
    if (typeof v === "boolean") out[k] = v;
  }
  return out;
}
function readEnabled(store, projectKey) {
  const map = asMap(store.read());
  return Object.hasOwn(map, projectKey) ? map[projectKey] : ENABLED_BY_DEFAULT;
}

// ../mcp/src/hook-pretooluse.ts
function main() {
  try {
    readFileSync(0, "utf8");
  } catch {
  }
  const env = process.env;
  const statePath = env.TOKENMAXED_STATE ?? (env.CLAUDE_PLUGIN_DATA ? join(env.CLAUDE_PLUGIN_DATA, "state.json") : "");
  const projectKey = env.TOKENMAXED_PROJECT ?? env.CLAUDE_PROJECT_DIR ?? "default";
  const disabledByEnv = env.TOKENMAXED_DISABLE === "1" || env.TOKENMAXED_DISABLE === "true";
  const store = {
    read: () => {
      if (!statePath || !existsSync(statePath)) return {};
      try {
        return JSON.parse(readFileSync(statePath, "utf8"));
      } catch {
        return {};
      }
    },
    write: () => {
    }
  };
  const enabled = !disabledByEnv && readEnabled(store, projectKey);
  const decision = preToolUseDecision(enabled);
  if (decision) process.stdout.write(JSON.stringify(decision));
}
try {
  main();
} catch {
}
process.exit(0);
