/**
 * F4 — bundle the TokenMaxed Cline adapter (CLI 3.x + VS Code extension 4.x).
 *
 * Cline contracts (verified July 2026):
 *   - MCP: cline_mcp_settings.json with a per-server env map (example ships
 *     with env.TOKENMAXED_HOST=cline). Tools surface as tokenmaxed__router_*
 *     on the CLI/SDK, and via use_mcp_tool on the VS Code extension.
 *   - File hooks: the ONLY blocking hook on both surfaces is PreToolUse.
 *     The VS Code extension requires an EXTENSIONLESS executable named
 *     exactly `PreToolUse` (Unix) / `PreToolUse.ps1` (Windows), so the hook
 *     bundles are CJS (an extensionless file parses as CJS) with a node
 *     shebang + exec bit; import.meta.url is rewritten to a __filename shim.
 *     TaskStart is blocking+injected on the extension, detached/ignored on
 *     the CLI (documented reduced surface).
 *   - NO turn-end blocking primitive exists on either surface (agent_end is
 *     observational) — there is deliberately NO review-loop hook here; the
 *     /tokenmaxed-review skill covers review on demand. Honesty over faking.
 *   - Skills: native SKILL.md (name must equal the dir; description ≤1024).
 *     `disable-model-invocation` is NOT part of Cline's frontmatter contract,
 *     so manual-only semantics are preserved as an explicit MANUAL-ONLY body
 *     preamble instead.
 */

import { build } from 'esbuild';
import { chmodSync, copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const mcpSrc = (f) => resolve(root, '../mcp/src', f);

const ESM_SHIM = [
  "import { createRequire as __cr } from 'node:module';",
  "import { fileURLToPath as __f } from 'node:url';",
  "import { dirname as __d } from 'node:path';",
  'const require = __cr(import.meta.url);',
  'const __filename = __f(import.meta.url);',
  'const __dirname = __d(__filename);',
].join('\n');

// Reference data + starters (same set the other host adapters ship).
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

// The MCP server bundle (ESM like the other hosts — launched by path from config).
await build({
  entryPoints: [mcpSrc('bin.ts')],
  outfile: resolve(root, 'server/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/cline-plugin/build.mjs — DO NOT EDIT. Bundled TokenMaxed MCP server (Cline).\n${ESM_SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'cline';`,
  },
});
console.error('[cline-plugin] bundled MCP server → server/index.mjs');

// Hook bundles: EXTENSIONLESS CJS executables (see header). import.meta.url is
// defined away to a __filename-based shim so ESM-flavored sources bundle clean.
async function bundleHook(entry, name, label) {
  const outfile = resolve(root, 'hooks', name);
  await build({
    entryPoints: [mcpSrc(entry)],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    define: { 'import.meta.url': '__importMetaUrl' },
    // DUAL-MODULE-SCOPE banner: node parses an extensionless file as CJS in a
    // bare directory (the normal installed case) but as ESM when a nearby
    // package.json says type:module (this repo). `var x = typeof x ...` keeps
    // the CJS wrapper params where they exist and synthesizes them in ESM
    // scope (process.getBuiltinModule needs node >= 22.3; Cline requires 22+).
    banner: {
      js: [
        '#!/usr/bin/env node',
        `// Generated by packages/cline-plugin/build.mjs — DO NOT EDIT. ${label}.`,
        "var __filename = typeof __filename !== 'undefined' ? __filename : process.argv[1];",
        "var require = typeof require !== 'undefined' ? require : process.getBuiltinModule('node:module').createRequire(__filename);",
        "var __dirname = typeof __dirname !== 'undefined' ? __dirname : require('node:path').dirname(__filename);",
        "var module = typeof module !== 'undefined' ? module : { exports: {} };",
        "var exports = typeof exports !== 'undefined' ? exports : module.exports;",
        "const __importMetaUrl = require('node:url').pathToFileURL(__filename).href;",
        "process.env.TOKENMAXED_HOST ??= 'cline';",
      ].join('\n'),
    },
  });
  chmodSync(outfile, 0o755);
  console.error(`[cline-plugin] bundled ${label} → hooks/${name}`);
}
await bundleHook('hook-cline-pretooluse.ts', 'PreToolUse', 'TokenMaxed PreToolUse gate (Cline)');
await bundleHook('hook-cline-taskstart.ts', 'TaskStart', 'TokenMaxed TaskStart banner (Cline)');

// --- generate skills from the Claude plugin's (single source of truth) ---------
const srcSkills = resolve(root, '../plugin/skills');
const outSkills = resolve(root, 'skills');
rmSync(outSkills, { recursive: true, force: true });
mkdirSync(outSkills, { recursive: true });

// ONE transform applied to body AND description alike.
const transform = (text) =>
  text
    // Tool names: Claude plugin-MCP format → Cline CLI server__tool naming (the
    // extension's use_mcp_tool indirection understands "the MCP tool X on
    // server tokenmaxed" from the same text).
    .replaceAll('mcp__plugin_tokenmaxed_tokenmaxed__', 'tokenmaxed__')
    // Command references: /tokenmaxed:foo → /tokenmaxed-foo (Cline skills are
    // invoked as /<skill-dir-name>).
    .replaceAll(/\/tokenmaxed:([a-z-]+)/g, '/tokenmaxed-$1')
    .replaceAll('Use the AskUserQuestion tool', 'Ask the user directly')
    .replaceAll('the AskUserQuestion tool', 'a direct question to the user')
    .replaceAll('start Claude Code', 'start Cline')
    .replaceAll('Claude stops delegating', 'the agent stops delegating')
    .replaceAll("Claude's `--dangerously-skip-permissions`", "Claude Code's `--dangerously-skip-permissions`")
    .replaceAll('Claude offloads', 'the agent offloads')
    .replaceAll('Claude invokes', 'the agent invokes')
    .replaceAll('Claude Code settings', 'Cline settings')
    .replaceAll('in Claude Code', 'in Cline');

const MANUAL_ONLY_NOTE =
  '> **MANUAL-ONLY:** run this skill only when the user EXPLICITLY invokes it ' +
  '(e.g. `/<skill-name>`) or explicitly asks for exactly this action. Never ' +
  'auto-activate it from task matching.\n\n';

for (const dir of readdirSync(srcSkills)) {
  const md = readFileSync(resolve(srcSkills, dir, 'SKILL.md'), 'utf8');
  const name = `tokenmaxed-${dir}`;
  const manualOnly = /^disable-model-invocation:\s*true/m.test(md);
  let out = transform(md)
    // Cline's frontmatter contract is name+description only — the Claude-only
    // flag is dropped; its SEMANTICS survive as the explicit body preamble.
    .replace(/^disable-model-invocation:.*\n/m, '');
  out = out.replace(/^---\n/, `---\nname: ${name}\n`);
  if (manualOnly) out = out.replace(/\n---\n/, `\n---\n\n${MANUAL_ONLY_NOTE}`);
  mkdirSync(resolve(outSkills, name), { recursive: true });
  writeFileSync(resolve(outSkills, name, 'SKILL.md'), out, 'utf8');
}
console.error(`[cline-plugin] generated ${readdirSync(outSkills).length} skills → ${outSkills}`);
