/**
 * E — bundle the TokenMaxed Codex CLI plugin. Mirrors packages/plugin/build.mjs:
 * ONE self-contained server bundle + hook bundles + reference data, all
 * COMMITTED (a marketplace/git install ships only tracked files; plugin.json's
 * .mcp.json launches `node ${PLUGIN_ROOT}/server/index.mjs`).
 *
 * The Codex hook I/O contract matches Claude Code's for PreToolUse (deny via
 * hookSpecificOutput.permissionDecision) and Stop (decision:"block" + reason),
 * and SessionStart's JSON envelope (hookSpecificOutput.additionalContext +
 * optional systemMessage) is ALSO the Codex contract — those bundle from the
 * SAME sources as the Claude plugin. Stop differs: Codex's schema is strict
 * (additionalProperties:false), so it bundles the hook-codex-stop entry.
 *
 * Skills are GENERATED from the Claude plugin's skills (single source of
 * truth) with two mechanical transforms: tool names
 * (mcp__plugin_tokenmaxed_tokenmaxed__router_X → tokenmaxed:router_X) and
 * command references (/tokenmaxed:name → $tokenmaxed-name), plus a `name:`
 * frontmatter field (Codex requires it) and Codex-appropriate invocation notes.
 */

import { build } from 'esbuild';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const mcpSrc = (f) => resolve(root, '../mcp/src', f);

const SHIM = [
  "import { createRequire as __cr } from 'node:module';",
  "import { fileURLToPath as __f } from 'node:url';",
  "import { dirname as __d } from 'node:path';",
  'const require = __cr(import.meta.url);',
  'const __filename = __f(import.meta.url);',
  'const __dirname = __d(__filename);',
].join('\n');

async function bundle(entry, outfile, label, shim = true) {
  await build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    // F: host identity default — hook processes don't inherit .mcp.json's env,
    // so every bundle self-identifies (an explicit TOKENMAXED_HOST still wins).
    banner: { js: `// Generated by packages/codex-plugin/build.mjs — DO NOT EDIT. ${label}.${shim ? `\n${SHIM}` : ''}\nprocess.env.TOKENMAXED_HOST ??= 'codex-cli';` },
  });
  console.error(`[codex-plugin] bundled ${label} → ${outfile}`);
}

// Reference data + starters (same set the Claude plugin ships).
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

await bundle(mcpSrc('bin.ts'), resolve(root, 'server/index.mjs'), 'Bundled TokenMaxed MCP server (Codex CLI)');
await bundle(mcpSrc('hook-pretooluse.ts'), resolve(root, 'hooks/pretooluse.mjs'), 'TokenMaxed PreToolUse gate (Codex CLI)', false);
await bundle(mcpSrc('hook-codex-stop.ts'), resolve(root, 'hooks/stop.mjs'), 'TokenMaxed Stop review loop (Codex CLI, strict schema)');
await bundle(mcpSrc('hook-sessionstart.ts'), resolve(root, 'hooks/sessionstart.mjs'), 'TokenMaxed SessionStart banner (Codex CLI — same JSON contract as Claude Code)');

// --- generate skills from the Claude plugin's (single source of truth) -----------
const srcSkills = resolve(root, '../plugin/skills');
const outSkills = resolve(root, 'skills');
rmSync(outSkills, { recursive: true, force: true });
mkdirSync(outSkills, { recursive: true });

for (const dir of readdirSync(srcSkills)) {
  const md = readFileSync(resolve(srcSkills, dir, 'SKILL.md'), 'utf8');
  const name = `tokenmaxed-${dir}`;
  // Claude's manual-only flag has no SKILL.md equivalent in Codex — its
  // SEMANTICS are preserved via agents/openai.yaml (allow_implicit_invocation:
  // false), so a state-changing command (yolo/off/prefer/…) can never be
  // selected implicitly by task matching.
  const manualOnly = /^disable-model-invocation:\s*true/m.test(md);
  let out = md
    // Tool names: Claude Code plugin-MCP format → Codex server:tool namespacing.
    .replaceAll('mcp__plugin_tokenmaxed_tokenmaxed__', 'tokenmaxed:')
    // Command references: /tokenmaxed:foo → $tokenmaxed-foo (Codex skill invocation).
    .replaceAll(/\/tokenmaxed:([a-z-]+)/g, '$$tokenmaxed-$1')
    .replace(/^disable-model-invocation:.*\n/m, '')
    // Host-language transforms (Claude-Code-specific instructions would be
    // wrong inside Codex; keep lane NAMES like "cheaper-Claude" untouched).
    .replaceAll('Use the AskUserQuestion tool', 'Ask the user directly')
    .replaceAll('the AskUserQuestion tool', 'a direct question to the user')
    .replaceAll('start Claude Code', 'start Codex')
    .replaceAll('Claude stops delegating', 'the agent stops delegating')
    .replaceAll("Claude's `--dangerously-skip-permissions`", "Claude Code's `--dangerously-skip-permissions` (Codex analogue: `--sandbox danger-full-access`)")
    .replaceAll('Claude offloads', 'the agent offloads')
    .replaceAll('Claude invokes', 'the agent invokes')
    .replaceAll('Claude Code settings', 'Codex config.toml')
    .replaceAll('in Claude Code', 'in Codex CLI');
  // Codex requires a `name:` frontmatter field.
  out = out.replace(/^---\n/, `---\nname: ${name}\n`);
  mkdirSync(resolve(outSkills, name), { recursive: true });
  writeFileSync(resolve(outSkills, name, 'SKILL.md'), out, 'utf8');
  if (manualOnly) {
    mkdirSync(resolve(outSkills, name, 'agents'), { recursive: true });
    writeFileSync(
      resolve(outSkills, name, 'agents/openai.yaml'),
      'policy:\n  allow_implicit_invocation: false\n',
      'utf8',
    );
  }
}
console.error(`[codex-plugin] generated ${readdirSync(outSkills).length} skills → ${outSkills}`);
