/**
 * F6 — bundle the TokenMaxed pi extension (earendil-works/pi >= 0.75, node >=
 * 22.19 — pi's own floor; contracts verified at repo HEAD 2026-07-11; pi's
 * extension API has ROUTINE breaking changes, so the README pins the verified
 * version).
 *
 * Layout (register BY PATH — no copying needed):
 *   extension/index.ts          ← the bundle (JS is valid TS; pi discovers
 *                                 `*.ts` and `<dir>/index.ts`, loads via jiti)
 *   extension/tokenmaxed-review.mjs ← the shared review child beside it
 *   prices.seed.json etc.       ← ONE LEVEL UP: the shared deps resolve
 *                                 reference data module-relative ('../'),
 *                                 which lands here when registered by path.
 *   skills/                     ← generated; add via settings.json "skills"
 *
 * In-process laws (pi loads extensions into its TUI process via jiti): the
 * bundle must NOT mutate process.env and must NOT contain spawnSync (the
 * review runs in the child) — both manifest-pinned.
 */

import { build } from 'esbuild';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const mcpSrc = (f) => resolve(root, '../mcp/src', f);

const ESM_SHIM = [
  "import { createRequire as __cr } from 'node:module';",
  "import { fileURLToPath as __f } from 'node:url';",
  "import { dirname as __d } from 'node:path';",
  'const require = __cr(import.meta.url);',
  'const __filename = __f(import.meta.url);',
  'const __dirname = __d(__filename);',
].join('\n');

// Reference data at the PACKAGE root (module-relative '../' from extension/).
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

// The extension bundle. Emitted as index.ts (JS is valid TS) because pi's
// discovery globs are *.ts / */index.ts; jiti loads it in-process. NO env
// banner (in-process — host identity threads via piExtensionEnv).
mkdirSync(resolve(root, 'extension'), { recursive: true });
await build({
  entryPoints: [mcpSrc('pi-extension.ts')],
  outfile: resolve(root, 'extension/index.ts'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/pi-extension/build.mjs — DO NOT EDIT. TokenMaxed pi extension (tools + gate + banner + review + statusline).\n${ESM_SHIM}`,
  },
});
console.error('[pi-extension] bundled extension → extension/index.ts');

// The review CHILD beside the bundle (a child process — env default correct).
await build({
  entryPoints: [mcpSrc('review-child-main.ts')],
  outfile: resolve(root, 'extension/tokenmaxed-review.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/pi-extension/build.mjs — DO NOT EDIT. TokenMaxed review child (pi).\n${ESM_SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'pi';`,
  },
});
console.error('[pi-extension] bundled review child → extension/tokenmaxed-review.mjs');

// The TOOL child (every registered tool executes here — the trusted CLI
// executor is spawnSync-based and must never run on pi's TUI event loop).
await build({
  entryPoints: [mcpSrc('pi-tool-main.ts')],
  outfile: resolve(root, 'extension/tokenmaxed-tool.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/pi-extension/build.mjs — DO NOT EDIT. TokenMaxed tool child (pi).\n${ESM_SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'pi';`,
  },
});
console.error('[pi-extension] bundled tool child → extension/tokenmaxed-tool.mjs');

// --- generate skills (pi implements the AgentSkills standard natively, incl.
// disable-model-invocation — manual-only survives as frontmatter) -------------
const srcSkills = resolve(root, '../plugin/skills');
const outSkills = resolve(root, 'skills');
rmSync(outSkills, { recursive: true, force: true });
mkdirSync(outSkills, { recursive: true });

const transform = (text) =>
  text
    // Tool names: Claude plugin-MCP format → the pi extension's native names.
    .replaceAll('mcp__plugin_tokenmaxed_tokenmaxed__', 'tokenmaxed_')
    // Command references: /tokenmaxed:foo → /skill:tokenmaxed-foo (pi's skill
    // slash-command dialect).
    .replaceAll(/\/tokenmaxed:([a-z-]+)/g, '/skill:tokenmaxed-$1')
    .replaceAll('Use the AskUserQuestion tool', 'Ask the user directly')
    .replaceAll('the AskUserQuestion tool', 'a direct question to the user')
    .replaceAll('start Claude Code', 'start pi')
    .replaceAll('Claude stops delegating', 'the agent stops delegating')
    .replaceAll("Claude's `--dangerously-skip-permissions`", "Claude Code's `--dangerously-skip-permissions`")
    .replaceAll('Claude offloads', 'the agent offloads')
    .replaceAll('Claude invokes', 'the agent invokes')
    .replaceAll('Claude Code settings', 'pi settings.json')
    .replaceAll('in Claude Code', 'in pi');

for (const dir of readdirSync(srcSkills)) {
  const md = readFileSync(resolve(srcSkills, dir, 'SKILL.md'), 'utf8');
  const name = `tokenmaxed-${dir}`;
  // disable-model-invocation is honored NATIVELY by pi — keep it verbatim.
  let out = transform(md);
  out = out.replace(/^---\n/, `---\nname: ${name}\n`);
  mkdirSync(resolve(outSkills, name), { recursive: true });
  writeFileSync(resolve(outSkills, name, 'SKILL.md'), out, 'utf8');
}
console.error(`[pi-extension] generated ${readdirSync(outSkills).length} skills → ${outSkills}`);
