/**
 * F3 — bundle the TokenMaxed OpenClaw adapter. Mirrors the other host adapters:
 * ONE self-contained MCP server bundle + ONE in-process Gateway plugin bundle +
 * the review child + reference data + generated skills, all COMMITTED.
 *
 * OpenClaw contracts (verified 2026.6/2026.7, July 2026):
 *   - Native plugin: openclaw.plugin.json manifest (checked in at the package
 *     root) + index.js entry (this bundle), loaded IN-PROCESS by the Gateway —
 *     so the plugin bundle must NOT mutate process.env and must NOT contain
 *     spawnSync (the review runs in the tokenmaxed-review.mjs child beside it).
 *     Install: `openclaw plugins install --link <this package dir>` (or add the
 *     dir to plugins.load.paths).
 *   - MCP server: ~/.openclaw/openclaw.json → mcp.servers.tokenmaxed with
 *     env: { TOKENMAXED_HOST: "openclaw" } (see openclaw.example.json). Tools
 *     surface as tokenmaxed__router_* (server__tool, double underscore).
 *   - Skills: OpenClaw consumes the AgentSkills SKILL.md format natively
 *     (including disable-model-invocation, which is KEPT — unlike hosts that
 *     needed a separate guard). Generated from the Claude plugin's skills with
 *     tool-name (mcp__plugin_tokenmaxed_tokenmaxed__X → tokenmaxed__X) +
 *     command-reference (/tokenmaxed:x → /tokenmaxed_x — OpenClaw command
 *     names sanitize to [a-z0-9_]) + host-language transforms.
 */

import { build } from 'esbuild';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const mcpSrc = (f) => resolve(root, '../mcp/src', f);

const SHIM = [
  "import { createRequire as __cr } from 'node:module';",
  "import { fileURLToPath as __f } from 'node:url';",
  "import { dirname as __d } from 'node:path';",
  'const require = __cr(import.meta.url);',
  'const __filename = __f(import.meta.url);',
  'const __dirname = __d(__filename);',
].join('\n');

// Reference data + starters (same set the other host adapters ship).
copyFileSync(resolve(root, '../../config/prices.seed.json'), resolve(root, 'prices.seed.json'));
copyFileSync(resolve(root, '../../config/capability-snapshot.v1.json'), resolve(root, 'capability-snapshot.v1.json'));
copyFileSync(resolve(root, '../mcp/lanes.starter.yaml'), resolve(root, 'lanes.starter.yaml'));
copyFileSync(resolve(root, '../mcp/policy.starter.yaml'), resolve(root, 'policy.starter.yaml'));

// The MCP server bundle (a child process — env default banner is correct here).
await build({
  entryPoints: [mcpSrc('bin.ts')],
  outfile: resolve(root, 'server/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/openclaw-plugin/build.mjs — DO NOT EDIT. Bundled TokenMaxed MCP server (OpenClaw).\n${SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'openclaw';`,
  },
});
console.error('[openclaw-plugin] bundled MCP server → server/index.mjs');

// The in-process Gateway plugin (NO env mutation, NO spawnSync — see header).
await build({
  entryPoints: [mcpSrc('openclaw-plugin.ts')],
  outfile: resolve(root, 'index.js'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/openclaw-plugin/build.mjs — DO NOT EDIT. TokenMaxed OpenClaw plugin (banner + routing gate + finalize review).\n${SHIM}`,
  },
});
console.error('[openclaw-plugin] bundled plugin → index.js');

// The review CHILD (spawned by the plugin so the spawnSync-based review path
// never blocks the Gateway's event loop). Ships NEXT TO index.js.
await build({
  entryPoints: [mcpSrc('review-child-main.ts')],
  outfile: resolve(root, 'tokenmaxed-review.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  banner: {
    js: `// Generated by packages/openclaw-plugin/build.mjs — DO NOT EDIT. TokenMaxed review child (OpenClaw).\n${SHIM}\nprocess.env.TOKENMAXED_HOST ??= 'openclaw';`,
  },
});
console.error('[openclaw-plugin] bundled review child → tokenmaxed-review.mjs');

// --- generate skills from the Claude plugin's (single source of truth) ---------
const srcSkills = resolve(root, '../plugin/skills');
const outSkills = resolve(root, 'skills');
rmSync(outSkills, { recursive: true, force: true });
mkdirSync(outSkills, { recursive: true });

// ONE transform applied to body AND description alike.
const transform = (text) =>
  text
    // Tool names: Claude Code plugin-MCP format → OpenClaw server__tool naming.
    .replaceAll('mcp__plugin_tokenmaxed_tokenmaxed__', 'tokenmaxed__')
    // Command references: /tokenmaxed:foo → /tokenmaxed_foo (OpenClaw command
    // names sanitize to [a-z0-9_]; '-' and ':' are not allowed).
    .replaceAll(/\/tokenmaxed:([a-z-]+)/g, (_, name) => `/tokenmaxed_${name.replaceAll('-', '_')}`)
    // Host-language transforms (keep lane NAMES like "cheaper-Claude" untouched).
    .replaceAll('Use the AskUserQuestion tool', 'Ask the user directly')
    .replaceAll('the AskUserQuestion tool', 'a direct question to the user')
    .replaceAll('start Claude Code', 'start OpenClaw')
    .replaceAll('Claude stops delegating', 'the agent stops delegating')
    .replaceAll("Claude's `--dangerously-skip-permissions`", "Claude Code's `--dangerously-skip-permissions`")
    .replaceAll('Claude offloads', 'the agent offloads')
    .replaceAll('Claude invokes', 'the agent invokes')
    .replaceAll('Claude Code settings', 'OpenClaw openclaw.json')
    .replaceAll('in Claude Code', 'in OpenClaw');

for (const dir of readdirSync(srcSkills)) {
  const md = readFileSync(resolve(srcSkills, dir, 'SKILL.md'), 'utf8');
  const name = `tokenmaxed-${dir}`;
  // OpenClaw supports disable-model-invocation natively — KEEP it (manual-only
  // skills stay manual-only). Only `name:` is added (required frontmatter).
  let out = transform(md);
  out = out.replace(/^---\n/, `---\nname: ${name}\n`);
  mkdirSync(resolve(outSkills, name), { recursive: true });
  writeFileSync(resolve(outSkills, name, 'SKILL.md'), out, 'utf8');
}
console.error(`[openclaw-plugin] generated ${readdirSync(outSkills).length} skills → ${outSkills}`);
